apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nodejs
spec:
  hosts:
  - "*"
  gateways:
  - nodejs-gateway
  http:
    - route:
      - destination:
          host: nodejs
          subset: production
        weight: 90
      - destination:
          host: nodejs
          subset: feature
        weight: 10
